### ISSUE TITLE
please make a new tag for 7.4 support

### ISSUE THREAD

**Issue by smknstd** [campaignmonitor/createsend-php#101]

**Comment by timbertens** [comment]
Can you please release the commit https://github.com/campaignmonitor/createsend-php/pull/100/commits/a0ffc3d16e061ce7bcd18d5756128233028b6275 as it fixes the 'curly bracket' issue that makes this component incompatible with php 7.4

**Comment by circa1977** [comment]
I just encountered this error, too. I'm relying on this package for e-commerce email notifications.

**Comment by henrypenny** [comment]
+1

**Comment by timbertens** [comment]
I've submitted the request to support at CampaignMonitor, let's see if this helps ...

**Comment by timbertens** [comment]
CampaignMonitor just confirmed me that they have released v6.1.1 of this package with the PHP7.4 merge into it.

**Comment by smknstd** [comment]
looks good to me https://github.com/campaignmonitor/createsend-php/commits/v6.1.1
