### ISSUE TITLE
ErrorCode 50 - Must supply a valid HTTP Basic Authorization header

### ISSUE THREAD

**Issue by Radon8472** [campaignmonitor/createsend-php#107]
Since some time we get the error

```json
{
  "Code": 50,
  "Message": "Must supply a valid HTTP Basic Authorization header"
}
```
A similar problem was reported in closed issues campaignmonitor/createsend-php#15 and campaignmonitor/createsend-php#33
I tried to fire a sample request like shown on [getting-started] with my own api-key, and I get the same response.

```php
  echo file_get_contents('https://api.createsend.com/api/v3.2/clients.json?pretty=true', false, stream_context_create(
    array('http'=>array(
    'method'=>"GET",
    'ignore_errors'=>true,
    'header'=> "Authorization: Basic ".base64_encode($auth['api_key'].':x')."\r\n"
    ))
  ));
```
I can ensure that:
- no proxy or firewall is stripping the `Authorization` header
- I have no trailing or leading whitespace in the APIKey string

This errorcode is not listed in [API Docs - response-status-codes], but I checked the `Authorization` that is delivered by you API class and by my exmpla with native php file_get_contents.
Both seem to send a valid `Basic` auth header, that contains my correct api-key.

Is it possible that there could be a problem with the API-Endpoint or any changes in the auth-methods?

[getting-started]: https://www.campaignmonitor.com/api/getting-started/#authenticating-api-key
[API Docs - response-status-codes]: https://www.campaignmonitor.com/api/getting-started/#response-status-codes

**Comment by machadoug** [comment]
I'm also facing this issue. I've updated to the latest API PHP Wrapper and the problem remains.

@Radon8472  did you get it fixed? If so, can you please share your solution?

**Comment by Radon8472** [comment]
@machadoug Yes, after talking to CM support i got the info that they disabled some api codes for security reasons, and that causes that errorcode.

According the [API-documentation](https://www.campaignmonitor.com/api/getting-started/#response-status-codes) I would expect such issues should return

```json
{
    "Code": 100,
    "Message": "Invalid API Key"
}
```

but it seems that this security disabled keys have a different code that is not listed in the docu 🙄

**Comment by Radon8472** [comment]
@machadoug today I finally could try it with the new api code.
Now getting clients works, but when I try to get a list I get an error in [transport.php].

Can you tell me how I can set the debug-level ?



[transport.php]: /campaignmonitor/createsend-php/blob/12a4c1f33b940775bde80ae1494036df06ed36d4/class/transport.php#L306

**Comment by adrenth** [comment]
I'm facing the same issue recently. I have not changed my code implementation, so there must be a change at API level?
