### ISSUE TITLE
TemplateID invalid

### ISSUE THREAD

**Issue by jonathanpuc** [campaignmonitor/createsend-php#125]
I've created a Template in Campaign Monitor and grabbed the ID from the url eg. https://xxx/templates/preview/51cb0dc3e2b60e4a?s=BECEB18AB5D6CF77

When calling 'create_from_template()', I get {"Code":4001,"Message":"Invalid TemplateID or the template doesn't exist"}.

Am I misunderstanding what Template ID is? I've tried to list the current templates by calling get_templates() with the Clients class but this just tells me invalid ClientID which is weird as the ClientID is working with other operations.

**Comment by abhishek-blackbaud** [comment]
Hey @jonathanpuc 

I am having similar issue with getting a template as well
https://api.createsend.com/api/v3.3/templates/template_Id.json
`CreateSend::Unauthorized (The CreateSend API responded with the following error - 4001: Invalid TemplateID or the template doesn't exist):`

Can you give some idea what was wrong or how you fixed this?

Thank You
