### ISSUE TITLE
Class Name Conflict?

### ISSUE THREAD

**Issue by nCrafts** [campaignmonitor/createsend-php#28]
This is my relevant code

```
require_once('campaign/csrest_general.php');
$auth = array('api_key' => $_POST['code']);
$wrap = new CS_REST_General($auth);
```

I am getting this error on the first line itself

```Fatal error: Cannot redeclare class cs_rest_wrapper_result in campaign/class/base_classes.php on line 19```

Any ideas? The code has not been edited in any way.

**Comment by asadighi** [comment]
Starting from V5.0.2 class name conflicts will not happen anymore.
