### ISSUE TITLE
impossible to set custom timeout

### ISSUE THREAD

**Issue by gemal** [campaignmonitor/createsend-php#30]
using: v3.1.3

I'm sending 1000 subscribers at a time to import() and I keep getting:

Fatal Error Error: Error making request with curl_error: Operation timed out after 10000 milliseconds with 0 bytes received in [CampaignMonitor\class\transport.php, line 158]

Why not do something like:

if (!defined(''CS_REST_CALL_TIMEOUT')) { 
define('CS_REST_CALL_TIMEOUT', 10); 
}

or something?

So it was possible to set a custom timeout

**Comment by nufyoot** [comment]
This was addressed in #36
