### ISSUE TITLE
Supplied examples: "Must supply a valid HTTP Basic Authorization header"

### ISSUE THREAD

**Issue by philipjohn** [campaignmonitor/createsend-php#33]
I am using the [supplied example](https://github.com/campaignmonitor/createsend-php#using-an-api-key) to test the API:

```
require_once 'csrest_general.php';

$auth = array('api_key' => 'your API key');
$wrap = new CS_REST_General($auth);

$result = $wrap->get_clients();
var_dump($result->response);
```

However, the response I get is;

```
array(
   'Code' => 50,
   'Message' => 'Must supply a valid HTTP Basic Authorization header',
)
```

I have also tried using the [supplied example for adding subscribers](https://github.com/campaignmonitor/createsend-php/blob/master/samples/subscriber/add.php), with the same result.

How do I set the Basic Auth header? Given the [docs](http://www.campaignmonitor.com/api/getting-started/#authenticating_with_an_api_key) say that Basic Auth simply requires the API key as the username and a blank password, I assumed the library would handle that if I just give it an API key, as the samples do.

**Comment by nijeshhirpara** [comment]
Hi @itgoeslikethis @philipjohn,

I am having similar issue.

```here is my code,
require_once '../../csrest_clients.php';

`$auth = array('api_key' => '1d29303abc99f50156f9fadf5447bd15');`
$wrap = new CS_REST_Clients($auth);

$result = $wrap->create(array(
    'CompanyName' => 'Test',
    'Country' => 'Australia',
    'Timezone' => '(GMT+09:30) Adelaide'
));

echo "Result of POST /api/v3.1/clients\n<br />";
if($result->was_successful()) {
    echo "Created with ID\n<br />".$result->response;
} else {
    echo 'Failed with code '.$result->http_status_code."\n<br /><pre>";
    var_dump($result->response);
    echo '</pre>';
}
```

**Comment by asadighi** [comment]
Is this exact excerpt from your code?

`$auth = array('api_key' => 'Your API Key');`

**Comment by itgoeslikethis** [comment]
Hi @nijeshhirpara ,

Unfortunately there could be a number of reasons that you're getting that response, but it in some way it indicates *something* wrong with the `Authorization` header that's coming through. You've said that you think the API key is correct, so here's a few options:
* There is a bit of trailing or leading whitespace in the APIKey string (eg `" abdcef12"`)
* A proxy or firewall is stripping the `Authorization` header from outgoing traffic from your server
* What you've put in as the APIKey is some other string (perhaps a Client-level APIKey - for creating Clients you need to have an Account-level key, or maybe just a ClientID)

Do you think it could be any of those?

**Comment by Radon8472** [comment]
Ich habe den Fehler mal in campaignmonitor/createsend-php#107 gemeldet.
Vermutlich liegt das Problem am API-Endpunkt.
