### ISSUE TITLE
transient network issues results in unhandleable fatal.

### ISSUE THREAD

**Issue by cabbey** [campaignmonitor/createsend-php#37]
When the server at `api.createsend.com` encounters an error, or is unable to successfully negotiate a network connection, the php sdk does a `trigger_error()` with level `E_USER_ERROR` (at https://github.com/campaignmonitor/createsend-php/blob/master/class/transport.php#L158 ). This results in an immediate fatal shutdown of the php process with no chance for higher level logic to attempt to do a graceful retry or other logic.

This makes the use of your sdk in larger server side applications rather dangerous. It would be wonderful if the sdk simply returned an error to the caller that indicated it had issues talking to the server and allow the higher level application code to make decisions about retries and/or aborting the processing loop for a while until the servers come back online.

**Comment by kai11** [comment]
Not tested, just a reminder for myself and potential starting point for others:

```php
function error_handler($level, $message, $file, $line, $context) {
    return $level === E_USER_ERROR; // if true will ignore PHP error handler and avoid blank screen
}
set_error_handler('error_handler');
```

**Comment by cabbey** [comment]
Just a note that when you set_error_handler() you should capture the current error handler, and in your error handler, if the error doesn't originate from your code, invoke the previously installed error handler with the passed in arguments.

**Comment by asadighi** [comment]
Starting at 5.0.1 we are throwing an exception instead of fatal error.

Thanks,
Aidin
