### ISSUE TITLE
Checkbox options no longer submitting

### ISSUE THREAD

**Issue by dougmorin** [campaignmonitor/createsend-php#41]
Checkbox options are no longer being passed to createsend when selected.  Has something changed?  Where is an example of the proper syntax required when sending checkboxes?

And just for the record, this is an existing website where the checkboxes used to be sent through, so it was working at one point in time.  The client just noticed that nothing was being sent through any longer.  I upgraded to the most recent version and it still does not work.

Thanks!
Doug

**Comment by dougmorin** [comment]
Also, it's worth noting that there are multiple custom fields on this form, and it's only the checkbox that isn't passing a value through.

**Comment by v3nt** [comment]
I know this was a while ago but dod you solve it somehow? Thanks.
