### ISSUE TITLE
add Subscribe - confirmed 201 - but not adding to the list

### ISSUE THREAD

**Issue by theoldcounty** [campaignmonitor/createsend-php#44]
I was using the add Subscribe function fine, but a few hours ago it stopped working.

The response indicates a successful entry - but when I view the list on campaign monitor the subscribers are blank.

 function addSubscriber($list_id, $emailAddress, $name, $title, $showName, $showDate, $showTime){
		//create subscriber
		$subscriber = array(
			'EmailAddress' => $emailAddress,
			'Name' => $name,
			'CustomFields' => array(
				array(
					'Key' => "Title",
					'Value' => $title
				),
				array(
					'Key' => "ShowName",
					'Value' => $showName
				),
				array(
					'Key' => "ShowDate",
					'Value' => $showDate
				),
				array(
					'Key' => "ShowTime",
					'Value' => $showTime
				)
			),
			'Resubscribe' => true,
			'RestartSubscriptionBasedAutoResponders' => true
		);

		//print_r($subscriber);

		$subwrap = new CS_REST_Subscribers($list_id, $this->auth);
		$result = $subwrap->add($subscriber); 
		//var_dump($result->response);

		echo "Result of POST /api/v3.1/subscribers/{list id}.{format}\n<br />";
		if($result->was_successful()) {
		    echo "Subscribed with code ".$result->http_status_code;
		} else {
		    echo 'Failed with code '.$result->http_status_code."\n<br /><pre>";
		    var_dump($result->response);
		    echo '</pre>';
		}
		return $result->response;
	}

**Comment by marbetschar** [comment]
Same problem over here. For some reason, adding new subscribers has just stopped working.
However, the response I receive is still a 201.

The code in charge for adding new subscribers looks like this:

    $wrap = new CS_REST_Subscribers($list,$auth);

    $result = $wrap->add(array(
        'EmailAddress' => $email,
        'Name' => $fullName,
        'Resubscribe' => true
    ));

What's going wrong?

**Comment by marbetschar** [comment]
@theoldcounty did you find any solution yet?

**Comment by marbetschar** [comment]
I've found that the subscribers are added, but there seems to be a lag between getting the 201 back and seeing the new subscriber in the list. So i revisited the documentation and seen the text:

```
The subscriber data is then passed into a processing queue in Campaign Monitor to be added.
For instantaneous adding or to add subscribers in bulk,
please use the Importing Many Subscribers method.
```

So this seems to be a desired behaviour due to the nature Campaign Monitor works internally.
Source: https://www.campaignmonitor.com/api/subscribers/

**Comment by nufyoot** [comment]
As mentioned by @marbetschar, the subscribers are added to a queue and processed independently from the API call. It looks like at the time there was some delay on Campaign Monitor's end that caused the queue processing to get behind for a bit.

@theoldcounty, can you confirm that the subscribers are there now?

**Comment by theoldcounty** [comment]
Its ok - it was missing some other parameter.
