### ISSUE TITLE
Unexpected response from Campaign Monitor API.

### ISSUE THREAD

**Issue by TomasHurtz** [campaignmonitor/createsend-php#69]
Getting no response from the API.

"Unexpected response from Campaign Monitor API."

It was all working great for some time - but suddenly this issue has come up.  I have not changed any files on my side and there does not appear to be anything new in the repository.

Could this be related to the issue mentioned here: https://github.com/campaignmonitor/createsend-php/issues/49#issuecomment-372496398

2017-10-20T14:49:06+00:00 CRITICAL Uncaught exception 'CurlException' with message 'Error making request with curl_error: Operation timed out after 10001 milliseconds with 0 bytes received' in /home/zzz/public_html/wpnew/wp-content/themes/zzz/assets/zzz/class/transport.php:174
Stack trace:
0 /home/zzz/public_html/wpnew/wp-content/themes/zzz/assets/zzz/class/base_classes.php(291): CS_REST_CurlTransport->make_call(Array)
1 /home/zzz/public_html/wpnew/wp-content/themes/zzz/assets/zzz/class/base_classes.php(234): CS_REST_Wrapper_Base->_call(Array, 'GET', 'https://api.cre...')
2 /home/zzz/public_html/wpnew/wp-content/themes/zzz/assets/zzz/csrest_subscribers.php(181): CS_REST_Wrapper_Base->get_request('https://api.cre...')
3 /home/zzz/public_html/wpnew/wp-content/themes/zzz/assets/zzz/cm-basic-subscriber-update.php(52): CS_REST_Subscribers->get('')

**Comment by catcher23** [comment]
@TomasHurtz  some API calls may take longer than 10 seconds, especially with larger requests. Updated the default time in this commit: https://github.com/campaignmonitor/createsend-php/commit/e4e0c4b37eacf55a77a8ae4488b7df3c9e3a4ace.
